### ISSUE TITLE
.configure issue

### ISSUE THREAD

**Issue by writing-shed** [codykerns/PurchasesHelper#2]
I don't think it should be declared 'static'

**Comment by codykerns** [comment]
@writing-shed thanks for the comments here - the intention here is to mimic the Purchases SDK, plus with only allowing one instance of CompatibilityAccessManager it feels cleaner. any downside to having it a static method on the class?

**Comment by writing-shed** [comment]
I raised the issue because you use the method as static with shared in the readMe file. For consistency I'd remove the static property.

**Comment by codykerns** [comment]
Ah, I missed that! I went ahead and just published this change in v0.1.4, and also included backwards compatibility for iOS 9.3.
