### ISSUE TITLE
Question about BackwardsCompatibilityEntitlement

### ISSUE THREAD

**Issue by wes-nz** [codykerns/PurchasesHelper#5]
Hi @codykerns,

First of all thank you for this very useful repo.

After reading [your article](https://www.revenuecat.com/blog/converting-a-paid-ios-app-to-subscriptions) and the [readme](https://github.com/codykerns/PurchasesHelper/blob/master/README.md) I am having a doubt.

On the article it sounds like `BackwardsCompatibilityEntitlement` requires all previous paid versions
```Swift
CompatibilityAccessManager.shared.register(entitlement:
	.init(entitlement: "premium", versions: ["1", "2", "3"])
)
```
but in the readme it sounds like only the latest paid version is necessary.
> For example, if your paid app was version 1.0 (50) and your subscription update is 1.1 (75), register your entitlement like the following:
```Swift
CompatibilityAccessManager.shared.configure(entitlement:
    .init(entitlement: "premium_access", versions: ["50"])
)
```

Looking at `CompatibilityAccessManager` `entitlementActiveInCompatibility()`, I would say the article is correct and all versions are needed?

Thanks.

**Comment by codykerns** [comment]
Thanks for the kind words, I'm glad you're finding it useful!

Yeah, the article is correct - you'll need *every* version number you want to support. If a version number isn't registered, it won't be considered for isActive. Apologies for the confusion here- I'll work on updating the readme to clarify this!
