### ISSUE TITLE
displayTitleRecurring for Year returns Annually

### ISSUE THREAD

**Issue by pnome** [codykerns/PurchasesHelper#6]
Thanks for providing these helpers. They're really useful.

I just have one issue...

I'm using `displayTitleRecurring` to pull the period so I can make my buy button say **"Start Monthly/Weekly/Lifetime Plan"**

The issue is that the Year period returns "Annually" instead of "Yearly".

**"Start Annually Plan**" doesn't make sense.

I believe it could be changed to Yearly without negatively affecting anyone else who is using it.

**Comment by codykerns** [comment]
Thanks for the feedback! I totally agree. I just merged a PR (#7) with this fix.
